// Datos de muestra para previsualizar la pantalla de Actividades como un
// gestor de tareas completo. Viven solo en el cliente, en memoria: no hay
// tabla en Supabase para esto todavía, es una demo visual de cómo quedaría.

export type ActivityType = "whatsapp" | "email" | "call" | "calendar" | "payment" | "document" | "review";
export type ActivityStatus = "Pendiente" | "En proceso" | "Completada" | "Cancelada" | "Programada";

export interface SampleActivity {
  id: string;
  type: ActivityType;
  title: string;
  context: string;
  patientName: string;
  patientCode: string;
  responsibleName: string;
  responsibleRole: string;
  daysOffset: number;
  time: string;
  status: ActivityStatus;
}

// Equipo de apoyo (recepción/administración), además de los profesionales
// clínicos ya existentes. Nombres de prueba, añadidos solo para esta vista.
export const SUPPORT_STAFF = [
  { name: "Marc Vidal", role: "Recepción" },
  { name: "Nerea Puig", role: "Administración" },
];

export const SAMPLE_ACTIVITIES: SampleActivity[] = [
  {
    id: "act-1",
    type: "whatsapp",
    title: "Confirmar cita por WhatsApp",
    context: "Cita: Laura Sánchez · 11:30",
    patientName: "Laura Sánchez",
    patientCode: "#P-000125",
    responsibleName: "Marc Vidal",
    responsibleRole: "Recepción",
    daysOffset: 0,
    time: "08:30",
    status: "Pendiente",
  },
  {
    id: "act-2",
    type: "email",
    title: "Enviar presupuesto",
    context: "Tratamiento: Implante unitario",
    patientName: "Carlos Martínez",
    patientCode: "#P-000124",
    responsibleName: "Marc Vidal",
    responsibleRole: "Recepción",
    daysOffset: 0,
    time: "09:15",
    status: "Pendiente",
  },
  {
    id: "act-3",
    type: "call",
    title: "Llamar seguimiento presupuesto",
    context: "Presupuesto: PR-00045",
    patientName: "María López",
    patientCode: "#P-000123",
    responsibleName: "Marc Vidal",
    responsibleRole: "Recepción",
    daysOffset: 0,
    time: "11:00",
    status: "Pendiente",
  },
  {
    id: "act-4",
    type: "calendar",
    title: "Recordatorio cita",
    context: "Cita: Ana Torres · 15:00",
    patientName: "Ana Torres",
    patientCode: "#P-000127",
    responsibleName: "Marc Vidal",
    responsibleRole: "Recepción",
    daysOffset: 0,
    time: "14:00",
    status: "Pendiente",
  },
  {
    id: "act-5",
    type: "payment",
    title: "Cobro pendiente",
    context: "Factura: FAC-00078",
    patientName: "Juan Pérez",
    patientCode: "#P-000118",
    responsibleName: "Nerea Puig",
    responsibleRole: "Administración",
    daysOffset: 0,
    time: "16:45",
    status: "Pendiente",
  },
  {
    id: "act-6",
    type: "document",
    title: "Revisión plan de tratamiento",
    context: "Tratamiento: Ortodoncia",
    patientName: "Carlos Mompo",
    patientCode: "#P-000113",
    responsibleName: "Marta Ruiz",
    responsibleRole: "Ortodoncia",
    daysOffset: 1,
    time: "10:00",
    status: "Pendiente",
  },
  {
    id: "act-7",
    type: "whatsapp",
    title: "Enviar recordatorio de revisión",
    context: "Tratamiento: Blanqueamiento",
    patientName: "Ana Torres",
    patientCode: "#P-000119",
    responsibleName: "Automatización",
    responsibleRole: "Sistema",
    daysOffset: 1,
    time: "12:00",
    status: "Programada",
  },
  {
    id: "act-8",
    type: "review",
    title: "Solicitar reseña",
    context: "Cita: María López · 10:00",
    patientName: "María López",
    patientCode: "#P-000121",
    responsibleName: "Automatización",
    responsibleRole: "Sistema",
    daysOffset: 2,
    time: "09:00",
    status: "Programada",
  },
  {
    id: "act-9",
    type: "call",
    title: "Llamar para reagendar",
    context: "Cita cancelada: 14 jul",
    patientName: "Laura Sánchez",
    patientCode: "#P-000125",
    responsibleName: "Marc Vidal",
    responsibleRole: "Recepción",
    daysOffset: 1,
    time: "11:30",
    status: "Pendiente",
  },
  {
    id: "act-10",
    type: "email",
    title: "Enviar informe de revisión",
    context: "Cita: Carlos Martínez · completada",
    patientName: "Carlos Martínez",
    patientCode: "#P-000124",
    responsibleName: "Pau Camps",
    responsibleRole: "Odontología general",
    daysOffset: 0,
    time: "07:30",
    status: "Completada",
  },
  {
    id: "act-11",
    type: "payment",
    title: "Confirmar pago financiado",
    context: "Factura: FAC-00081",
    patientName: "Juan Pérez",
    patientCode: "#P-000118",
    responsibleName: "Nerea Puig",
    responsibleRole: "Administración",
    daysOffset: 1,
    time: "13:00",
    status: "Pendiente",
  },
  {
    id: "act-12",
    type: "document",
    title: "Preparar plan de implantes",
    context: "Tratamiento: Implantología",
    patientName: "María López",
    patientCode: "#P-000123",
    responsibleName: "Álvaro Costa",
    responsibleRole: "Implantología",
    daysOffset: 2,
    time: "10:30",
    status: "Pendiente",
  },
  {
    id: "act-13",
    type: "calendar",
    title: "Recordatorio cita",
    context: "Cita: Carlos Mompo · 09:00",
    patientName: "Carlos Mompo",
    patientCode: "#P-000113",
    responsibleName: "Marc Vidal",
    responsibleRole: "Recepción",
    daysOffset: 0,
    time: "08:00",
    status: "Cancelada",
  },
  {
    id: "act-14",
    type: "whatsapp",
    title: "Confirmar cita por WhatsApp",
    context: "Cita: Ana Torres · 17:00",
    patientName: "Ana Torres",
    patientCode: "#P-000127",
    responsibleName: "Marc Vidal",
    responsibleRole: "Recepción",
    daysOffset: -1,
    time: "09:00",
    status: "Completada",
  },
  {
    id: "act-15",
    type: "call",
    title: "Seguimiento post-tratamiento",
    context: "Tratamiento: Higiene dental",
    patientName: "Laura Sánchez",
    patientCode: "#P-000125",
    responsibleName: "Isabel Ferrer",
    responsibleRole: "Higiene dental",
    daysOffset: 2,
    time: "12:30",
    status: "Pendiente",
  },
];
